/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pk4Tech;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author kaka
 */
public class First extends javax.swing.JFrame {

        
    /**
     * Creates new form First
     */
    public First() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jButtonHome = new javax.swing.JButton();
        jButtonContact = new javax.swing.JButton();
        jButtonAbout = new javax.swing.JButton();
        jButtonDonate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        HomePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ContactPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        AboutPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonGit = new javax.swing.JButton();
        jButtonFacebook = new javax.swing.JButton();
        jButtonInsta = new javax.swing.JButton();
        jButtonPin = new javax.swing.JButton();
        DonatePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Footer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("By Pk4Tech");
        setBounds(new java.awt.Rectangle(400, 150, 650, 400));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));

        Header.setBackground(new java.awt.Color(102, 102, 102));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        jButtonHome.setBackground(new java.awt.Color(102, 102, 102));
        jButtonHome.setText("Home");
        jButtonHome.setFocusable(false);
        jButtonHome.setRequestFocusEnabled(false);
        jButtonHome.setRolloverEnabled(false);
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jButtonContact.setBackground(new java.awt.Color(102, 102, 102));
        jButtonContact.setText("Contact");
        jButtonContact.setFocusable(false);
        jButtonContact.setRequestFocusEnabled(false);
        jButtonContact.setRolloverEnabled(false);
        jButtonContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContactActionPerformed(evt);
            }
        });

        jButtonAbout.setBackground(new java.awt.Color(102, 102, 102));
        jButtonAbout.setText("About");
        jButtonAbout.setBorderPainted(false);
        jButtonAbout.setFocusable(false);
        jButtonAbout.setRequestFocusEnabled(false);
        jButtonAbout.setRolloverEnabled(false);
        jButtonAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAboutActionPerformed(evt);
            }
        });

        jButtonDonate.setBackground(new java.awt.Color(102, 102, 102));
        jButtonDonate.setText("Donate");
        jButtonDonate.setBorderPainted(false);
        jButtonDonate.setDefaultCapable(false);
        jButtonDonate.setFocusable(false);
        jButtonDonate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDonateActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("-");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(140, 140, 140)
                .addComponent(jButtonHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonContact)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAbout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDonate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHome)
                    .addComponent(jButtonContact)
                    .addComponent(jButtonAbout)
                    .addComponent(jButtonDonate))
                .addContainerGap())
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setLayout(new java.awt.CardLayout());

        HomePanel.setBackground(new java.awt.Color(204, 0, 51));

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Tap To open Calculator");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel2)
                .addContainerGap(486, Short.MAX_VALUE))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel2)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        jPanel6.add(HomePanel, "card2");

        ContactPanel.setBackground(new java.awt.Color(204, 0, 51));

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("2nd Panel");

        javax.swing.GroupLayout ContactPanelLayout = new javax.swing.GroupLayout(ContactPanel);
        ContactPanel.setLayout(ContactPanelLayout);
        ContactPanelLayout.setHorizontalGroup(
            ContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContactPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(169, 169, 169))
        );
        ContactPanelLayout.setVerticalGroup(
            ContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactPanelLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.add(ContactPanel, "card3");

        AboutPanel.setBackground(new java.awt.Color(204, 0, 51));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pk4Tech/Pk4Tech.jpg"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("About Me!");

        jScrollPane1.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(204, 0, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Hi! Myself Pradip Nandan Raut, I am developer in Java and Web Application like PHP, Asp.net, Javascript.  ");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonGit.setBackground(new java.awt.Color(102, 102, 102));
        jButtonGit.setText("Git");
        jButtonGit.setToolTipText("Facebook Link");
        jButtonGit.setFocusable(false);
        jButtonGit.setRequestFocusEnabled(false);
        jButtonGit.setRolloverEnabled(false);
        jButtonGit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGitActionPerformed(evt);
            }
        });

        jButtonFacebook.setBackground(new java.awt.Color(102, 102, 102));
        jButtonFacebook.setText("Facebook");
        jButtonFacebook.setToolTipText("Facebook Link");
        jButtonFacebook.setFocusable(false);
        jButtonFacebook.setRequestFocusEnabled(false);
        jButtonFacebook.setRolloverEnabled(false);
        jButtonFacebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFacebookActionPerformed(evt);
            }
        });

        jButtonInsta.setBackground(new java.awt.Color(102, 102, 102));
        jButtonInsta.setText("Insta");
        jButtonInsta.setToolTipText("Facebook Link");
        jButtonInsta.setFocusable(false);
        jButtonInsta.setRequestFocusEnabled(false);
        jButtonInsta.setRolloverEnabled(false);
        jButtonInsta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInstaActionPerformed(evt);
            }
        });

        jButtonPin.setBackground(new java.awt.Color(102, 102, 102));
        jButtonPin.setText("Pintress");
        jButtonPin.setToolTipText("Facebook Link");
        jButtonPin.setFocusable(false);
        jButtonPin.setRequestFocusEnabled(false);
        jButtonPin.setRolloverEnabled(false);
        jButtonPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AboutPanelLayout = new javax.swing.GroupLayout(AboutPanel);
        AboutPanel.setLayout(AboutPanelLayout);
        AboutPanelLayout.setHorizontalGroup(
            AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboutPanelLayout.createSequentialGroup()
                .addGroup(AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AboutPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(171, 171, 171))
                    .addGroup(AboutPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)))
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(AboutPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButtonFacebook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGit)
                .addGap(18, 18, 18)
                .addComponent(jButtonInsta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AboutPanelLayout.setVerticalGroup(
            AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboutPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(42, 42, 42)
                .addGroup(AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGit)
                    .addComponent(jButtonInsta)
                    .addComponent(jButtonPin)
                    .addComponent(jButtonFacebook))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPanel6.add(AboutPanel, "card4");

        DonatePanel.setBackground(new java.awt.Color(204, 0, 51));

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Donate!");

        javax.swing.GroupLayout DonatePanelLayout = new javax.swing.GroupLayout(DonatePanel);
        DonatePanel.setLayout(DonatePanelLayout);
        DonatePanelLayout.setHorizontalGroup(
            DonatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DonatePanelLayout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jLabel6)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        DonatePanelLayout.setVerticalGroup(
            DonatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DonatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(261, Short.MAX_VALUE))
        );

        jPanel6.add(DonatePanel, "card5");

        Footer.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButtonDonateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDonateActionPerformed
        HomePanel.setVisible(false);
        ContactPanel.setVisible(false);
        AboutPanel.setVisible(false);
        DonatePanel.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDonateActionPerformed

    private void jButtonAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAboutActionPerformed
        // TODO add your handling code here:
        HomePanel.setVisible(false);
        ContactPanel.setVisible(false);
        AboutPanel.setVisible(true);
        DonatePanel.setVisible(false);
    }//GEN-LAST:event_jButtonAboutActionPerformed

    private void jButtonContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContactActionPerformed
        // TODO add your handling code here:
        HomePanel.setVisible(false);
        ContactPanel.setVisible(true);
        AboutPanel.setVisible(false);
        DonatePanel.setVisible(false);
    }//GEN-LAST:event_jButtonContactActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        HomePanel.setVisible(true);
        ContactPanel.setVisible(false);
        AboutPanel.setVisible(false);
        DonatePanel.setVisible(false);
    }//GEN-LAST:event_jButtonHomeActionPerformed
int xx, yy;

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        yy = evt.getY(); 

    }//GEN-LAST:event_HeaderMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        // TODO add your handling code here:
        int x= evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_HeaderMouseDragged

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Runtime rs= Runtime.getRuntime();
        try{
//        rs.exec(new String[] {"cmd", "/k","start"});
//        Runtime.getRuntime().exec ("cmd /c start cmd.exe /K \" dir && ping localhost\ "");
//        rs.exec(diskpart.exe);
        rs.exec("calc");
        }
        catch(IOException e){
        System.out.println(e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked
        Desktop d = Desktop.getDesktop();
    private void jButtonGitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGitActionPerformed
        
        try {
            d.browse(new URI("http://bit.ly/2Yl6ax8"));
            // TODO add your handling code here:
        } catch (URISyntaxException ex) {
            Logger.getLogger(First.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(First.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGitActionPerformed

    private void jButtonFacebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFacebookActionPerformed
        // TODO add your handling code here:
        try {
            d.browse(new URI("http://bit.ly/2Jw0rRe"));
            // TODO add your handling code here:
        } catch (URISyntaxException ex) {
            Logger.getLogger(First.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(First.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonFacebookActionPerformed

    private void jButtonInstaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInstaActionPerformed
        // TODO add your handling code here:
        try {
            d.browse(new URI("http://bit.ly/2VSsJMh"));
            // TODO add your handling code here:
        } catch (URISyntaxException ex) {
            Logger.getLogger(First.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(First.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonInstaActionPerformed

    private void jButtonPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPinActionPerformed
        // TODO add your handling code here:
        try {
            d.browse(new URI("http://bit.ly/2LyQRzy"));
            // TODO add your handling code here:
        } catch (URISyntaxException ex) {
            Logger.getLogger(First.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(First.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new First().setVisible(true);
           
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutPanel;
    private javax.swing.JPanel ContactPanel;
    private javax.swing.JPanel DonatePanel;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JButton jButtonAbout;
    private javax.swing.JButton jButtonContact;
    private javax.swing.JButton jButtonDonate;
    private javax.swing.JButton jButtonFacebook;
    private javax.swing.JButton jButtonGit;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonInsta;
    private javax.swing.JButton jButtonPin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
